"""Initial migration

Revision ID: fb0799022ea9
Revises: 
Create Date: 2025-09-16 15:47:50.858514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb0799022ea9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city',
    sa.Column('city_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('city_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('city_id')
    )
    op.create_table('maintenance_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('permissions',
    sa.Column('permission_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('permission_id')
    )
    op.create_table('repair_status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('status_id')
    )
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('vehicle_state',
    sa.Column('state_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_table('person',
    sa.Column('person_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('city_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['city.city_id'], ),
    sa.PrimaryKeyConstraint('person_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('vehicles',
    sa.Column('vehicle_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('plate', sa.String(length=20), nullable=False),
    sa.Column('current_state_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['current_state_id'], ['vehicle_state.state_id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.person_id'], ),
    sa.PrimaryKeyConstraint('vehicle_id'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('maintenance',
    sa.Column('maintenance_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('type', sa.Enum('Preventivo', 'Correctivo'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['maintenance_status.status_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('maintenance_id')
    )
    op.create_table('repair',
    sa.Column('repair_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('reported_issue', sa.String(length=255), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_id'], ['repair_status.status_id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.vehicle_id'], ),
    sa.PrimaryKeyConstraint('repair_id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('maintenance_checklist_item',
    sa.Column('checklist_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('maintenance_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Completado', 'Requiere ajuste'), nullable=True),
    sa.ForeignKeyConstraint(['maintenance_id'], ['maintenance.maintenance_id'], ),
    sa.PrimaryKeyConstraint('checklist_item_id')
    )
    op.create_table('repair_checklist_item',
    sa.Column('checklist_item_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('Pendiente', 'Completado', 'Requiere ajuste'), nullable=True),
    sa.ForeignKeyConstraint(['repair_id'], ['repair.repair_id'], ),
    sa.PrimaryKeyConstraint('checklist_item_id')
    )
    op.create_table('repair_parts',
    sa.Column('repair_part_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repair_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('Cliente', 'Proveedor'), nullable=False),
    sa.ForeignKeyConstraint(['repair_id'], ['repair.repair_id'], ),
    sa.PrimaryKeyConstraint('repair_part_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repair_parts')
    op.drop_table('repair_checklist_item')
    op.drop_table('maintenance_checklist_item')
    op.drop_table('user_roles')
    op.drop_table('repair')
    op.drop_table('maintenance')
    op.drop_table('vehicles')
    op.drop_table('user')
    op.drop_table('role_permissions')
    op.drop_table('person')
    op.drop_table('vehicle_state')
    op.drop_table('roles')
    op.drop_table('repair_status')
    op.drop_table('permissions')
    op.drop_table('maintenance_status')
    op.drop_table('city')
    # ### end Alembic commands ###
